//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convertor.proxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxy.ConverterSoap")]
    public interface ConverterSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fToc", ReplyAction="*")]
        double fToc(double f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fTok", ReplyAction="*")]
        double fTok(double f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cTof", ReplyAction="*")]
        double cTof(double c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cTok", ReplyAction="*")]
        double cTok(double c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kTof", ReplyAction="*")]
        double kTof(double k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kToc", ReplyAction="*")]
        double kToc(double k);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConverterSoapChannel : Convertor.proxy.ConverterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConverterSoapClient : System.ServiceModel.ClientBase<Convertor.proxy.ConverterSoap>, Convertor.proxy.ConverterSoap {
        
        public ConverterSoapClient() {
        }
        
        public ConverterSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConverterSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConverterSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConverterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double fToc(double f) {
            return base.Channel.fToc(f);
        }
        
        public double fTok(double f) {
            return base.Channel.fTok(f);
        }
        
        public double cTof(double c) {
            return base.Channel.cTof(c);
        }
        
        public double cTok(double c) {
            return base.Channel.cTok(c);
        }
        
        public double kTof(double k) {
            return base.Channel.kTof(k);
        }
        
        public double kToc(double k) {
            return base.Channel.kToc(k);
        }
    }
}
